/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 steam_controller_2025.glb -T 
Files: steam_controller_2025.glb [5.75MB] > F:\My Documents\Sites\articles-gamepad-helper-demo-website\public\models\steam_controller_2025-transformed.glb [608.67KB] (89%)
Author: Ranguel (https://sketchfab.com/Ranguel)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/steam-controller-2025-fe10b1da83e54dae953f15d898ad6197
Title: Steam Controller 2025
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelSteamController2025(props) {
  const { nodes, materials } = useGLTF('models/steam_controller_2025-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_5.geometry} material={materials.Ink_ABXY_texture} rotation={[1.518, 0, 0]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.Plastic_ABXY_texture} rotation={[1.518, 0, 0]} />
      <mesh geometry={nodes.Object_11.geometry} material={materials['Plastic_D-pad_texture']} rotation={[1.641, 0, 0]} />
      <mesh geometry={nodes.Object_13.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.Object_14.geometry} material={materials['Plastic_Track-pad_texture']} />
      <mesh geometry={nodes.Object_20.geometry} material={materials.Rubber_L3R3_texture} />
      <mesh geometry={nodes.Object_28.geometry} material={materials.PaletteMaterial002} />
      <mesh geometry={nodes.Object_29.geometry} material={materials.PaletteMaterial003} />
      <mesh geometry={nodes.Object_32.geometry} material={materials.Ink_button_texture} />
      <mesh geometry={nodes.Object_35.geometry} material={materials.Copper_pins_texture} />
      <mesh geometry={nodes.Object_42.geometry} material={materials.Plastic_shell_texture} />
      <mesh geometry={nodes.Object_43.geometry} material={materials.Ink_shell_texture} />
    </group>
  )
}

useGLTF.preload('models/steam_controller_2025-transformed.glb')
